// Paige's Game Room — 90s Five puzzle bank
// Exactly 100 hand-picked five-letter 90s pop-culture answers.
window.PGR90S_PUZZLES = [
  {"id": 1, "answer": "SONIC", "category": "Video Games", "clue": "Blue, fast, and very Sega."},
  {"id": 2, "answer": "MARIO", "category": "Video Games", "clue": "Nintendo plumber with a red cap."},
  {"id": 3, "answer": "ZELDA", "category": "Video Games", "clue": "The princess at the center of a legendary Nintendo series."},
  {"id": 4, "answer": "KIRBY", "category": "Video Games", "clue": "Pink Nintendo hero with a huge appetite."},
  {"id": 5, "answer": "CRASH", "category": "Video Games", "clue": "Bandicoot who became a PlayStation mascot."},
  {"id": 6, "answer": "SPYRO", "category": "Video Games", "clue": "Small purple dragon from the original PlayStation era."},
  {"id": 7, "answer": "YOSHI", "category": "Video Games", "clue": "Mario’s green dinosaur pal."},
  {"id": 8, "answer": "PEACH", "category": "Video Games", "clue": "Princess of the Mushroom Kingdom."},
  {"id": 9, "answer": "WARIO", "category": "Video Games", "clue": "Mario’s greedy yellow-and-purple rival."},
  {"id": 10, "answer": "SAMUS", "category": "Video Games", "clue": "Armored bounty hunter from Metroid."},
  {"id": 11, "answer": "CLOUD", "category": "Video Games", "clue": "Spiky-haired hero of Final Fantasy VII."},
  {"id": 12, "answer": "QUAKE", "category": "Video Games", "clue": "1996 PC shooter from id Software."},
  {"id": 13, "answer": "WORMS", "category": "Video Games", "clue": "Tiny teams, big weapons, turn-based chaos."},
  {"id": 14, "answer": "BANJO", "category": "Video Games", "clue": "Bear half of a famous N64 duo."},
  {"id": 15, "answer": "SOLID", "category": "Video Games", "clue": "The middle word in a huge 1998 stealth-game title."},
  {"id": 16, "answer": "DARIA", "category": "TV & Cartoons", "clue": "Deadpan teen who spun off from Beavis and Butt-Head."},
  {"id": 17, "answer": "URKEL", "category": "TV & Cartoons", "clue": "Family Matters neighbor known for suspenders and “Did I do that?”"},
  {"id": 18, "answer": "BUFFY", "category": "TV & Cartoons", "clue": "Sunnydale’s vampire slayer."},
  {"id": 19, "answer": "ANGEL", "category": "TV & Cartoons", "clue": "Buffy’s brooding vampire with a soul."},
  {"id": 20, "answer": "PINKY", "category": "TV & Cartoons", "clue": "One half of a lab-mouse duo trying to take over the world."},
  {"id": 21, "answer": "BRAIN", "category": "TV & Cartoons", "clue": "The ambitious half of Pinky’s lab-mouse duo."},
  {"id": 22, "answer": "KELSO", "category": "TV & Cartoons", "clue": "Ashton Kutcher’s lovable doofus on That ’70s Show."},
  {"id": 23, "answer": "KENAN", "category": "TV & Cartoons", "clue": "Nickelodeon star paired with Kel."},
  {"id": 24, "answer": "ROCKO", "category": "TV & Cartoons", "clue": "Wallaby with a Modern Life."},
  {"id": 25, "answer": "SAVED", "category": "TV & Cartoons", "clue": "First word of the Bayside High sitcom title."},
  {"id": 26, "answer": "FRESH", "category": "TV & Cartoons", "clue": "First word of Will Smith’s Bel-Air sitcom title."},
  {"id": 27, "answer": "POWER", "category": "TV & Cartoons", "clue": "First word in the 1993 team of color-coded Rangers."},
  {"id": 28, "answer": "GOOSE", "category": "TV & Cartoons", "clue": "First half of R.L. Stine’s kid-horror series title."},
  {"id": 29, "answer": "PARTY", "category": "TV & Cartoons", "clue": "First word of the Fox drama about five siblings."},
  {"id": 30, "answer": "OPRAH", "category": "TV & Cartoons", "clue": "Daytime talk-show powerhouse of the decade."},
  {"id": 31, "answer": "RICKI", "category": "TV & Cartoons", "clue": "First name of a major 90s daytime talk-show host."},
  {"id": 32, "answer": "ROSIE", "category": "TV & Cartoons", "clue": "First name of the comedian whose daytime show began in 1996."},
  {"id": 33, "answer": "JESSE", "category": "TV & Cartoons", "clue": "Uncle ____ on Full House."},
  {"id": 34, "answer": "BECKY", "category": "TV & Cartoons", "clue": "Aunt ____ on Full House."},
  {"id": 35, "answer": "DYLAN", "category": "TV & Cartoons", "clue": "Luke Perry’s Beverly Hills, 90210 character."},
  {"id": 36, "answer": "GHOST", "category": "Movies", "clue": "1990 romance with pottery and a supernatural twist."},
  {"id": 37, "answer": "SPEED", "category": "Movies", "clue": "1994 action movie built around a city bus."},
  {"id": 38, "answer": "SEVEN", "category": "Movies", "clue": "1995 thriller whose title is often stylized with a number."},
  {"id": 39, "answer": "FARGO", "category": "Movies", "clue": "1996 snowy crime film from the Coen brothers."},
  {"id": 40, "answer": "BLADE", "category": "Movies", "clue": "1998 vampire-hunter superhero movie."},
  {"id": 41, "answer": "SPAWN", "category": "Movies", "clue": "1997 comic-book antihero movie."},
  {"id": 42, "answer": "HOCUS", "category": "Movies", "clue": "First word of the 1993 Sanderson-sisters movie."},
  {"id": 43, "answer": "MULAN", "category": "Movies", "clue": "Disney heroine who takes her father’s place in the army."},
  {"id": 44, "answer": "WOODY", "category": "Movies", "clue": "Cowboy toy voiced by Tom Hanks."},
  {"id": 45, "answer": "SIMBA", "category": "Movies", "clue": "Young lion who becomes king."},
  {"id": 46, "answer": "BELLE", "category": "Movies", "clue": "Book-loving heroine of Beauty and the Beast."},
  {"id": 47, "answer": "BEAST", "category": "Movies", "clue": "Cursed prince in a 1991 Disney classic."},
  {"id": 48, "answer": "GENIE", "category": "Movies", "clue": "Blue wish-granter in Aladdin."},
  {"id": 49, "answer": "JAFAR", "category": "Movies", "clue": "Aladdin villain with a cobra staff."},
  {"id": 50, "answer": "ROBIN", "category": "Movies", "clue": "Batman’s sidekick shared the title of a 1997 movie."},
  {"id": 51, "answer": "JUICE", "category": "Movies", "clue": "1992 crime drama starring Tupac Shakur."},
  {"id": 52, "answer": "RONIN", "category": "Movies", "clue": "1998 action thriller with famous car chases."},
  {"id": 53, "answer": "BOUND", "category": "Movies", "clue": "1996 neo-noir crime thriller from the Wachowskis."},
  {"id": 54, "answer": "KEVIN", "category": "Movies", "clue": "First name of the kid left Home Alone."},
  {"id": 55, "answer": "ETHAN", "category": "Movies", "clue": "Tom Cruise’s Mission: Impossible character."},
  {"id": 56, "answer": "SPICE", "category": "Music", "clue": "The Girls who told everyone what they really, really wanted."},
  {"id": 57, "answer": "OASIS", "category": "Music", "clue": "Britpop band behind “Wonderwall.”"},
  {"id": 58, "answer": "JEWEL", "category": "Music", "clue": "Singer-songwriter behind “You Were Meant for Me.”"},
  {"id": 59, "answer": "USHER", "category": "Music", "clue": "R&B singer who broke out as a teen in the 90s."},
  {"id": 60, "answer": "SNOOP", "category": "Music", "clue": "Rapper who debuted with Doggystyle."},
  {"id": 61, "answer": "JANET", "category": "Music", "clue": "Jackson sibling behind the janet. era."},
  {"id": 62, "answer": "TUPAC", "category": "Music", "clue": "Rapper also known as 2Pac."},
  {"id": 63, "answer": "BJORK", "category": "Music", "clue": "Icelandic artist behind Debut and Post."},
  {"id": 64, "answer": "STING", "category": "Music", "clue": "Former Police frontman with a huge 90s solo career."},
  {"id": 65, "answer": "FAITH", "category": "Music", "clue": "First name of country star Hill."},
  {"id": 66, "answer": "TONIC", "category": "Music", "clue": "Band behind “If You Could Only See.”"},
  {"id": 67, "answer": "BLINK", "category": "Music", "clue": "First word in the pop-punk trio’s name ending in 182."},
  {"id": 68, "answer": "CREEP", "category": "Music", "clue": "A 90s hit title shared by TLC and Radiohead."},
  {"id": 69, "answer": "LOSER", "category": "Music", "clue": "Beck’s breakout 1994 hit."},
  {"id": 70, "answer": "ALIVE", "category": "Music", "clue": "Pearl Jam song from Ten."},
  {"id": 71, "answer": "VOGUE", "category": "Music", "clue": "Madonna hit that became a dance-floor command."},
  {"id": 72, "answer": "CREAM", "category": "Music", "clue": "Prince hit released in 1991."},
  {"id": 73, "answer": "MAMBO", "category": "Music", "clue": "First word in Lou Bega’s 1999 “No. 5” hit."},
  {"id": 74, "answer": "NSYNC", "category": "Music", "clue": "Boy band featuring Justin Timberlake."},
  {"id": 75, "answer": "FIONA", "category": "Music", "clue": "First name of singer-songwriter Apple."},
  {"id": 76, "answer": "FURBY", "category": "Toys & Trends", "clue": "Big-eyed electronic pet that became a 1998 craze."},
  {"id": 77, "answer": "BOPIT", "category": "Toys & Trends", "clue": "Toy that tells you to twist it, pull it, and do this."},
  {"id": 78, "answer": "KOOSH", "category": "Toys & Trends", "clue": "Rubbery ball made of colorful strands."},
  {"id": 79, "answer": "POLLY", "category": "Toys & Trends", "clue": "First name of the tiny-pocket playset doll."},
  {"id": 80, "answer": "TROLL", "category": "Toys & Trends", "clue": "Wild-haired dolls that came roaring back in the 90s."},
  {"id": 81, "answer": "SURGE", "category": "Snacks & Drinks", "clue": "Neon-green citrus soda Coca-Cola launched in 1997."},
  {"id": 82, "answer": "NOKIA", "category": "Tech", "clue": "Phone brand famous for nearly indestructible handsets."},
  {"id": 83, "answer": "PAGER", "category": "Tech", "clue": "Pocket device that told you who needed a callback."},
  {"id": 84, "answer": "MODEM", "category": "Tech", "clue": "Noisy box that got the family computer online."},
  {"id": 85, "answer": "YAHOO", "category": "Tech", "clue": "Purple web portal and search brand launched in the 90s."},
  {"id": 86, "answer": "EMAIL", "category": "Tech", "clue": "The message format that started replacing letters and faxes."},
  {"id": 87, "answer": "CDROM", "category": "Tech", "clue": "Shiny computer disc format used for games and encyclopedias."},
  {"id": 88, "answer": "PLAID", "category": "Fashion", "clue": "Pattern strongly tied to grunge shirts."},
  {"id": 89, "answer": "FLARE", "category": "Fashion", "clue": "Jeans shape that widened toward the ankle."},
  {"id": 90, "answer": "KHAKI", "category": "Fashion", "clue": "Mall-era pants color that became office-casual shorthand."},
  {"id": 91, "answer": "CARGO", "category": "Fashion", "clue": "Pocket-heavy pants that were everywhere late in the decade."},
  {"id": 92, "answer": "BAGGY", "category": "Fashion", "clue": "The fit of a lot of 90s jeans and streetwear."},
  {"id": 93, "answer": "FROST", "category": "Fashion", "clue": "What happened to the tips of plenty of 90s hair."},
  {"id": 94, "answer": "LEVIS", "category": "Fashion", "clue": "Classic denim brand with a huge 90s presence."},
  {"id": 95, "answer": "GUESS", "category": "Fashion", "clue": "Denim-and-fashion brand known for black-and-white ads."},
  {"id": 96, "answer": "TYSON", "category": "Sports", "clue": "Heavyweight boxer whose name dominated 90s headlines."},
  {"id": 97, "answer": "TIGER", "category": "Sports", "clue": "First name/nickname of Woods, who won the 1997 Masters."},
  {"id": 98, "answer": "VENUS", "category": "Sports", "clue": "Williams sister who reached the 1997 U.S. Open final."},
  {"id": 99, "answer": "VIPER", "category": "Cars", "clue": "Dodge supercar that became a 90s poster favorite."},
  {"id": 100, "answer": "SUPRA", "category": "Cars", "clue": "Toyota performance icon made famous by 90s tuner culture."},
];
